In [1]:
import numpy as np
import pandas as pd
import random

In [2]:
arr = np.random.randint(1,10, (3,3))
arr

array([[2, 2, 4],
       [8, 3, 9],
       [7, 5, 1]])

In [3]:
arr = np.eye(3, dtype='int')
arr

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [4]:
arr = np.zeros((3,3), dtype='int')
arr

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [5]:
arr = np.empty((3,3), dtype='int')
arr

array([[ 544434464,  544501614, 1936028272],
       [ 745827941, 1937075488, 1634214004],
       [1931502966,  543518049, 1735288172]])

In [6]:
arr = np.ones((3,3), dtype='int')
arr

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [7]:
arr.reshape((1,9))

array([[1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [8]:
x = [*range(1, 10, 2)]
x

[1, 3, 5, 7, 9]

In [9]:
x = np.arange(0 ,10, 2)
x

array([0, 2, 4, 6, 8])

In [10]:
np.arange(1, 6.5, 0.5)

array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. ])

In [11]:
lst = range(10)
print(lst)

range(0, 10)


In [12]:
x = np.linspace(0 ,10, 5)
x

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [13]:
df = pd.read_excel("DataSets/Lab1data.xlsx")
df.head()

Stu ID  Gender   Age  Quantitative  Verbal  Technical  Interview  Total  \
0   A892    Male  31.0            22    33.0         35         29    119   
1   A985    Male  28.0            46    55.0         70         70    241   
2   A950  Female  27.0            56    68.0         54         26    204   
3   A768    Male  33.0            22    68.0         40         49    179   
4   A482  Female  34.0            38    23.0         46         62    169   

   Results  
0        0  
1        1  
2        1  
3        0  
4        0

In [14]:
df.shape

(12, 9)

In [15]:
df.columns

Index(['Stu ID', 'Gender', 'Age', 'Quantitative', 'Verbal', 'Technical',
       'Interview', 'Total', 'Results'],
      dtype='object')

In [16]:
df.dtypes

Stu ID           object
Gender           object
Age             float64
Quantitative      int64
Verbal          float64
Technical         int64
Interview         int64
Total             int64
Results           int64
dtype: object

In [17]:
df.describe()

Age  Quantitative     Verbal  Technical  Interview       Total  \
count  11.000000     12.000000  11.000000  12.000000  12.000000   12.000000   
mean   30.090909     45.000000  50.727273  48.500000  41.166667  186.916667   
std     2.300198     17.331002  15.060484  13.304135  17.708926   37.497778   
min    27.000000     22.000000  23.000000  30.000000  22.000000  119.000000   
25%    28.000000     34.250000  42.500000  37.000000  25.500000  172.000000   
50%    30.000000     44.500000  55.000000  47.000000  38.500000  188.000000   
75%    31.500000     56.000000  62.000000  57.500000  52.250000  209.500000   
max    34.000000     72.000000  69.000000  70.000000  70.000000  241.000000   

         Results  
count  12.000000  
mean    0.416667  
std     0.514929  
min     0.000000  
25%     0.000000  
50%     0.000000  
75%     1.000000  
max     1.000000

In [18]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12 entries, 0 to 11
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   Stu ID        12 non-null     object 
 1   Gender        11 non-null     object 
 2   Age           11 non-null     float64
 3   Quantitative  12 non-null     int64  
 4   Verbal        11 non-null     float64
 5   Technical     12 non-null     int64  
 6   Interview     12 non-null     int64  
 7   Total         12 non-null     int64  
 8   Results       12 non-null     int64  
dtypes: float64(2), int64(5), object(2)
memory usage: 996.0+ bytes


In [19]:
df.isnull().sum()

Stu ID          0
Gender          1
Age             1
Quantitative    0
Verbal          1
Technical       0
Interview       0
Total           0
Results         0
dtype: int64

In [20]:
df[df.duplicated()]

Stu ID Gender   Age  Quantitative  Verbal  Technical  Interview  Total  \
10   A593   Male  28.0            43    56.0         65         24    188   

    Results  
10        0

In [21]:
df = df.dropna()

In [22]:
df.isnull().sum()

Stu ID          0
Gender          0
Age             0
Quantitative    0
Verbal          0
Technical       0
Interview       0
Total           0
Results         0
dtype: int64

In [23]:
df['Age'] = df['Age'].astype('int64')

In [24]:
df.dtypes

Stu ID           object
Gender           object
Age               int64
Quantitative      int64
Verbal          float64
Technical         int64
Interview         int64
Total             int64
Results           int64
dtype: object

In [25]:
df['Results'].unique()

array([0, 1], dtype=int64)

In [26]:
df.nunique()

Stu ID          10
Gender           2
Age              8
Quantitative     8
Verbal           8
Technical       10
Interview       10
Total            9
Results          2
dtype: int64

In [27]:
df.Gender.value_counts()

Gender
Male      6
Female    5
Name: count, dtype: int64

In [28]:
type(df['Age'])


pandas.core.series.Series

In [30]:
df_cat = df.select_dtypes(object)
df_cat

Stu ID  Gender
0    A892    Male
1    A985    Male
2    A950  Female
3    A768    Male
4    A482  Female
5    A816    Male
6    A387  Female
7    A735  Female
8    A368  Female
9    A593    Male
10   A593    Male

In [81]:
random.seed(10)
print(random.random())

0.5714025946899135


In [84]:
random.seed(25)
print(random.random())

0.376962302390386
